use anyhow::Result;

fn default_harness() -> String {
    "stdin".to_string()
}
fn default_corpus_dir() -> String {
    "./phaedra-corpus".to_string()
}
fn default_crash_dir() -> String {
    "./phaedra-crashes".to_string()
}
fn default_timeout() -> u64 {
    5
}
fn default_jobs() -> usize {
    1
}
fn default_ollama_url() -> String {
    "http://localhost:11434".to_string()
}
fn default_ollama_model() -> String {
    "llama3.2".to_string()
}
fn default_seed_count() -> usize {
    16
}
fn default_socket_addr() -> String {
    "127.0.0.1:7777".to_string()
}
fn default_socket_proto() -> String {
    "tcp".to_string()
}
fn default_socket_read_bytes() -> usize {
    4096
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PhaedraConfig {
    pub target: String,
    #[serde(default = "default_harness")]
    pub harness: String,
    #[serde(default = "default_corpus_dir")]
    pub corpus_dir: String,
    #[serde(default = "default_crash_dir")]
    pub crash_dir: String,
    #[serde(default = "default_timeout")]
    pub timeout_secs: u64,
    #[serde(default = "default_jobs")]
    pub jobs: usize,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub schema: Option<String>,
    #[serde(default = "default_ollama_url")]
    pub ollama_url: String,
    #[serde(default = "default_ollama_model")]
    pub ollama_model: String,
    #[serde(default = "default_seed_count")]
    pub seed_count: usize,
    #[serde(default = "default_socket_addr")]
    pub socket_addr: String,
    #[serde(default = "default_socket_proto")]
    pub socket_proto: String,
    #[serde(default = "default_socket_read_bytes")]
    pub socket_read_bytes: usize,
}

pub fn load_config(path: &std::path::Path) -> Result<PhaedraConfig> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| anyhow::anyhow!("Failed to read config {:?}: {}", path, e))?;
    let config: PhaedraConfig = toml::from_str(&content)
        .map_err(|e| anyhow::anyhow!("Failed to parse config {:?}: {}", path, e))?;
    Ok(config)
}

pub fn save_config(config: &PhaedraConfig, path: &std::path::Path) -> Result<()> {
    let toml_str = toml::to_string(config)
        .map_err(|e| anyhow::anyhow!("Failed to serialize config: {}", e))?;
    let header = "# Phaedra campaign configuration\n\
                  # Generated by `phaedra init` — edit as needed\n\
                  # Run with: phaedra fuzz --config phaedra.toml\n\n";
    let content = format!("{}{}", header, toml_str);
    std::fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_save_and_load_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("phaedra.toml");
        let cfg = PhaedraConfig {
            target: "/bin/echo".to_string(),
            harness: "stdin".to_string(),
            corpus_dir: "./corpus".to_string(),
            crash_dir: "./crashes".to_string(),
            timeout_secs: 10,
            jobs: 2,
            description: Some("test target".to_string()),
            schema: None,
            ollama_url: "http://localhost:11434".to_string(),
            ollama_model: "llama3.2".to_string(),
            seed_count: 8,
            socket_addr: "127.0.0.1:9999".to_string(),
            socket_proto: "tcp".to_string(),
            socket_read_bytes: 1024,
        };
        save_config(&cfg, &path).unwrap();
        let loaded = load_config(&path).unwrap();
        assert_eq!(loaded.target, cfg.target);
        assert_eq!(loaded.timeout_secs, cfg.timeout_secs);
        assert_eq!(loaded.jobs, cfg.jobs);
        assert_eq!(loaded.description, cfg.description);
        assert_eq!(loaded.seed_count, cfg.seed_count);
        assert_eq!(loaded.socket_addr, cfg.socket_addr);
    }

    #[test]
    fn test_saved_file_has_comment_header() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("phaedra.toml");
        let cfg = PhaedraConfig {
            target: "/bin/cat".to_string(),
            harness: default_harness(),
            corpus_dir: default_corpus_dir(),
            crash_dir: default_crash_dir(),
            timeout_secs: default_timeout(),
            jobs: default_jobs(),
            description: None,
            schema: None,
            ollama_url: default_ollama_url(),
            ollama_model: default_ollama_model(),
            seed_count: default_seed_count(),
            socket_addr: default_socket_addr(),
            socket_proto: default_socket_proto(),
            socket_read_bytes: default_socket_read_bytes(),
        };
        save_config(&cfg, &path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("# Phaedra"), "file should start with comment header");
    }

    #[test]
    fn test_load_nonexistent_file_errors() {
        let result = load_config(std::path::Path::new("/nonexistent/phaedra.toml"));
        assert!(result.is_err());
    }

    #[test]
    fn test_defaults_are_valid() {
        let minimal = r#"target = "/bin/echo""#;
        let cfg: PhaedraConfig = toml::from_str(minimal).unwrap();
        assert_eq!(cfg.target, "/bin/echo");
        assert_eq!(cfg.harness, "stdin");
        assert_eq!(cfg.timeout_secs, 5);
        assert_eq!(cfg.jobs, 1);
        assert_eq!(cfg.ollama_url, "http://localhost:11434");
        assert_eq!(cfg.seed_count, 16);
        assert!(cfg.description.is_none());
        assert!(cfg.schema.is_none());
    }
}
